on:
  push:
    branches:
      - main
  pull_request:

name: golangci-lint

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
          skip-build-cache: true
          skip-pkg-cache: true
          args: --build-tags "containers_image_openpgp containers_image_ostree" --skip-dirs internal/pkg/staticfiles

